// Generated by CoffeeScript 1.4.0
(function() {

  this.rendactive = function(template, createDataTemplate) {
    var createStream, data, dataTemplate, destroy, eventMap, fragment, latestData, mark, unsubscribe;
    eventMap = {};
    createStream = function(selector) {
      var bus;
      bus = new Bacon.Bus();
      eventMap[selector] = bus.push;
      return bus;
    };
    dataTemplate = createDataTemplate(createStream);
    latestData = null;
    data = Bacon.combineTemplate(dataTemplate);
    unsubscribe = data.onValue(function(v) {
      return latestData = v;
    });
    mark = null;
    fragment = Spark.render(function() {
      return Spark.createLandmark({
        destroyed: unsubscribe,
        created: function() {
          return mark = this;
        }
      }, function() {
        var html;
        html = Spark.isolate(function() {
          var ctx;
          ctx = Meteor.deps.Context.current;
          ctx.onInvalidate(data.changes().onValue(function() {
            return ctx.invalidate();
          }));
          return template(latestData);
        });
        return Spark.attachEvents(eventMap, html);
      });
    });
    destroy = function() {
      return mark && Spark.finalize(mark.firstNode(), mark.lastNode());
    };
    return {
      fragment: fragment,
      dataTemplate: dataTemplate,
      destroy: destroy
    };
  };

}).call(this);
