// Generated by CoffeeScript 1.4.0
(function() {

  this.rendactive = function(template, createDataTemplate) {
    var createStream, data, dataTemplate, eventMap, fragment, latestData;
    eventMap = {};
    createStream = function(selector) {
      var bus;
      bus = new Bacon.Bus();
      eventMap[selector] = bus.push;
      return bus;
    };
    dataTemplate = createDataTemplate(createStream);
    latestData = null;
    data = Bacon.combineTemplate(dataTemplate);
    data.onValue(function(v) {
      return latestData = v;
    });
    fragment = Spark.render(function() {
      var html;
      html = Spark.isolate(function() {
        var ctx;
        ctx = Meteor.deps.Context.current;
        data.changes().take(1).onValue(function() {
          return ctx.invalidate();
        });
        return template(latestData);
      });
      return Spark.attachEvents(eventMap, html);
    });
    return {
      fragment: fragment,
      dataTemplate: dataTemplate
    };
  };

}).call(this);
